version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout  # This step checks out your source code

      - run:
          name: Hello, World!  # Display a message
          command: echo "Hello, World!"
